-- ============================================================
-- DEVOMETRICS -- PENDING MIGRATIONS: none
--
-- Everything through 0179 is applied and verified live (2026-09-24).
-- When a new migration is written, put its full SQL here under a header
-- and remove this note.
-- ============================================================
