-- ============================================================
-- DEVOMETRICS -- PENDING MIGRATIONS: none
--
-- Everything through 0183 is applied and verified live (2026-09-25).
-- Add the next migration's block here (and keep its header comment
-- current) when one is written.
-- ============================================================
