-- ============================================================
-- DEVOMETRICS -- PENDING MIGRATIONS: none
--
-- Everything through 0195 is applied and verified live (2026-10-09).
-- (0195 contact form abuse protection.)
--
-- Optional tidy-up: the live verification of 0195 left 3 labelled test
-- inquiries. Safe to run any time:
--   delete from public.contact_inquiries where name like 'AUDIT TEST%' or message like 'AUDIT TEST%';
-- ============================================================
