"use client";

import { useRef, useState, useTransition } from "react";
import * as XLSX from "xlsx";
import { UserPlus, Upload } from "lucide-react";
import { inviteEmployee, revokeInvite, bulkInviteEmployees, type BulkInviteRow, type BulkInviteResult } from "@/lib/organizations/actions";

const fieldStyle: React.CSSProperties = {
  background: "rgba(255,255,255,0.05)",
  border: "1px solid rgba(255,255,255,0.1)",
  borderRadius: 8,
  padding: "10px 14px",
  fontSize: 14,
  color: "var(--text)",
  outline: "none",
  width: "100%",
};

const labelStyle: React.CSSProperties = {
  fontSize: 11,
  fontWeight: 600,
  color: "var(--text-muted)",
  marginBottom: 4,
  display: "block",
};

function modeButtonStyle(active: boolean): React.CSSProperties {
  return {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: active ? "var(--teal)" : "transparent",
    color: active ? "#0A0F1E" : "var(--text-muted)",
    border: "none",
    borderRadius: 6,
    width: 34,
    height: 30,
    cursor: "pointer",
  };
}

// Accepts a range of header spellings ("Manager Email", "manager_email",
// "ManagerEmail") since this is filled in by hand in Excel/Sheets, not
// generated by another part of this app — normalizing to a bare
// alphanumeric key lets all of those match the same field.
function normalizeHeader(h: string): string {
  return h.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const HEADER_MAP: Record<string, keyof BulkInviteRow> = {
  email: "email",
  title: "title",
  jobtitle: "title",
  department: "department",
  country: "country",
  managername: "managerName",
  manager: "managerName",
  manageremail: "managerEmail",
  businessunit: "businessUnit",
  location: "location",
};

function parseWorkbook(data: ArrayBuffer): BulkInviteRow[] {
  const workbook = XLSX.read(data, { type: "array" });
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const raw = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" });

  return raw.map((rawRow) => {
    const row: BulkInviteRow = { email: "" };
    for (const [header, value] of Object.entries(rawRow)) {
      const field = HEADER_MAP[normalizeHeader(header)];
      if (!field) continue;
      const text = String(value ?? "").trim();
      if (text) row[field] = text;
    }
    return row;
  });
}

function downloadTemplate() {
  const worksheet = XLSX.utils.json_to_sheet([
    {
      Email: "jane@company.com",
      Title: "Product Manager",
      Department: "Product",
      Country: "Egypt",
      "Manager Name": "Amara Osei",
      "Manager Email": "amara@company.com",
      "Business Unit": "Growth",
      Location: "Cairo",
    },
  ]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Employees");
  XLSX.writeFile(workbook, "devometrics-employee-import-template.xlsx");
}

export default function InviteEmployeeForm({
  organizationId,
  pendingInvites,
}: {
  organizationId: string;
  pendingInvites: { id: string; email: string; title: string | null; department: string | null; country: string | null }[];
}) {
  const [mode, setMode] = useState<"single" | "import">("single");

  // Single-add fields
  const [email, setEmail] = useState("");
  const [title, setTitle] = useState("");
  const [department, setDepartment] = useState("");
  const [country, setCountry] = useState("");
  const [managerName, setManagerName] = useState("");
  const [managerEmail, setManagerEmail] = useState("");
  const [businessUnit, setBusinessUnit] = useState("");
  const [location, setLocation] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  // Import fields
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importRows, setImportRows] = useState<BulkInviteRow[]>([]);
  const [importFileName, setImportFileName] = useState<string | null>(null);
  const [importError, setImportError] = useState<string | null>(null);
  const [importResults, setImportResults] = useState<BulkInviteResult[] | null>(null);
  const [isImporting, startImportTransition] = useTransition();

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    startTransition(async () => {
      const result = await inviteEmployee(
        organizationId,
        email,
        title,
        department,
        country,
        managerName,
        managerEmail,
        businessUnit,
        location
      );
      if (result?.error) {
        setError(result.error);
      } else {
        setEmail("");
        setTitle("");
        setDepartment("");
        setCountry("");
        setManagerName("");
        setManagerEmail("");
        setBusinessUnit("");
        setLocation("");
      }
    });
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    setImportError(null);
    setImportResults(null);
    setImportFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const rows = parseWorkbook(reader.result as ArrayBuffer).filter((r) => r.email);
        if (rows.length === 0) {
          setImportError("No rows with an Email column value were found in that file.");
          setImportRows([]);
          return;
        }
        setImportRows(rows);
      } catch {
        setImportError("Could not read that file — make sure it's a .csv or .xlsx export.");
        setImportRows([]);
      }
    };
    reader.onerror = () => setImportError("Could not read that file.");
    reader.readAsArrayBuffer(file);
  }

  function submitImport() {
    setImportError(null);
    startImportTransition(async () => {
      const result = await bulkInviteEmployees(organizationId, importRows);
      if (result.error) {
        setImportError(result.error);
        return;
      }
      setImportResults(result.results ?? []);
      setImportRows([]);
      setImportFileName(null);
    });
  }

  return (
    <div style={{ background: "var(--navy-mid)", border: "1px solid var(--border)", borderRadius: 16, padding: 24 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12, marginBottom: 4 }}>
        <h2 style={{ fontSize: 15, fontWeight: 700, color: "var(--text)" }}>Invite employees</h2>
        <div style={{ display: "flex", background: "rgba(255,255,255,0.05)", border: "1px solid var(--border)", borderRadius: 8, padding: 3, gap: 2 }}>
          <button type="button" onClick={() => setMode("single")} title="Add one employee" aria-label="Add one employee" style={modeButtonStyle(mode === "single")}>
            <UserPlus size={15} />
          </button>
          <button type="button" onClick={() => setMode("import")} title="Import from file" aria-label="Import from file" style={modeButtonStyle(mode === "import")}>
            <Upload size={15} />
          </button>
        </div>
      </div>
      <p style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.5 }}>
        They&apos;ll get an email invite and be automatically attached to your company the moment
        they sign up with that address — no separate invite code needed.
      </p>

      {mode === "single" ? (
        <form onSubmit={handleSubmit}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 10, marginBottom: 14 }}>
            <div>
              <label style={labelStyle}>Email *</label>
              <input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="employee@company.com" style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Job title</label>
              <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Department</label>
              <input type="text" value={department} onChange={(e) => setDepartment(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Country</label>
              <input type="text" value={country} onChange={(e) => setCountry(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Manager name</label>
              <input type="text" value={managerName} onChange={(e) => setManagerName(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Manager email</label>
              <input type="email" value={managerEmail} onChange={(e) => setManagerEmail(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Business unit</label>
              <input type="text" value={businessUnit} onChange={(e) => setBusinessUnit(e.target.value)} style={fieldStyle} />
            </div>
            <div>
              <label style={labelStyle}>Location</label>
              <input type="text" value={location} onChange={(e) => setLocation(e.target.value)} style={fieldStyle} />
            </div>
          </div>
          <button
            type="submit"
            disabled={isPending}
            style={{
              background: "var(--teal)",
              color: "#0A0F1E",
              border: "none",
              borderRadius: 8,
              padding: "10px 20px",
              fontSize: 14,
              fontWeight: 700,
              cursor: "pointer",
              opacity: isPending ? 0.6 : 1,
            }}
          >
            {isPending ? "Sending…" : "Send invite"}
          </button>
          {error && <p style={{ color: "#f87171", fontSize: 13, marginTop: 10 }}>{error}</p>}
        </form>
      ) : (
        <div>
          <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 12 }}>
            <input ref={fileInputRef} type="file" accept=".csv,.xlsx,.xls" onChange={handleFileChange} style={{ display: "none" }} id="employee-import-input" />
            <label
              htmlFor="employee-import-input"
              style={{
                display: "inline-flex",
                alignItems: "center",
                background: "rgba(255,255,255,0.05)",
                border: "1px solid var(--border)",
                borderRadius: 8,
                padding: "10px 16px",
                fontSize: 13,
                fontWeight: 700,
                color: "var(--text)",
                cursor: "pointer",
              }}
            >
              Choose .csv or .xlsx file
            </label>
            <button
              type="button"
              onClick={downloadTemplate}
              style={{ background: "none", border: "none", color: "var(--teal)", fontSize: 12, fontWeight: 600, cursor: "pointer", textDecoration: "underline" }}
            >
              Download template
            </button>
          </div>
          {importFileName && <p style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 10 }}>{importFileName}</p>}
          {importError && <p style={{ color: "#f87171", fontSize: 13, marginBottom: 10 }}>{importError}</p>}

          {importRows.length > 0 && (
            <div style={{ marginBottom: 14 }}>
              <p style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 8 }}>
                Found {importRows.length} row{importRows.length === 1 ? "" : "s"} with an email — review before importing:
              </p>
              <div style={{ maxHeight: 220, overflowY: "auto", border: "1px solid var(--border)", borderRadius: 8 }}>
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
                  <thead>
                    <tr style={{ background: "rgba(255,255,255,0.03)" }}>
                      <th style={{ textAlign: "left", padding: "8px 10px", color: "var(--text-muted)" }}>Email</th>
                      <th style={{ textAlign: "left", padding: "8px 10px", color: "var(--text-muted)" }}>Title</th>
                      <th style={{ textAlign: "left", padding: "8px 10px", color: "var(--text-muted)" }}>Department</th>
                      <th style={{ textAlign: "left", padding: "8px 10px", color: "var(--text-muted)" }}>Manager</th>
                    </tr>
                  </thead>
                  <tbody>
                    {importRows.map((r, i) => (
                      <tr key={`${r.email}-${i}`} style={{ borderTop: "1px solid var(--border)" }}>
                        <td style={{ padding: "8px 10px", color: "var(--text)" }}>{r.email}</td>
                        <td style={{ padding: "8px 10px", color: "var(--text-muted)" }}>{r.title || "—"}</td>
                        <td style={{ padding: "8px 10px", color: "var(--text-muted)" }}>{r.department || "—"}</td>
                        <td style={{ padding: "8px 10px", color: "var(--text-muted)" }}>{r.managerName || "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <button
                type="button"
                onClick={submitImport}
                disabled={isImporting}
                style={{
                  marginTop: 12,
                  background: "var(--teal)",
                  color: "#0A0F1E",
                  border: "none",
                  borderRadius: 8,
                  padding: "10px 20px",
                  fontSize: 14,
                  fontWeight: 700,
                  cursor: "pointer",
                  opacity: isImporting ? 0.6 : 1,
                }}
              >
                {isImporting ? "Importing…" : `Import ${importRows.length} employee${importRows.length === 1 ? "" : "s"}`}
              </button>
            </div>
          )}

          {importResults && (
            <div style={{ fontSize: 13, color: "var(--text)" }}>
              <p style={{ marginBottom: 6 }}>
                ✓ {importResults.filter((r) => r.status === "invited").length} invited
                {importResults.some((r) => r.status !== "invited") && (
                  <>
                    {" — "}
                    {importResults.filter((r) => r.status === "duplicate").length} already invited,{" "}
                    {importResults.filter((r) => r.status === "invalid").length} skipped (no valid email)
                  </>
                )}
              </p>
            </div>
          )}
        </div>
      )}

      {pendingInvites.length > 0 && (
        <div style={{ marginTop: 20 }}>
          <p style={{ fontSize: 12, fontWeight: 700, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
            Pending ({pendingInvites.length})
          </p>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {pendingInvites.map((invite) => (
              <div key={invite.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13 }}>
                <span style={{ color: "var(--text)" }}>
                  {invite.email}
                  {[invite.title, invite.department, invite.country].filter(Boolean).length > 0 && (
                    <span style={{ color: "var(--text-muted)" }}>
                      {" "}
                      — {[invite.title, invite.department, invite.country].filter(Boolean).join(" · ")}
                    </span>
                  )}
                </span>
                <button
                  type="button"
                  onClick={() => startTransition(() => revokeInvite(invite.id))}
                  style={{ background: "none", border: "none", color: "var(--text-muted)", fontSize: 12, cursor: "pointer" }}
                >
                  Revoke
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
