// Primary browsing section, not a hard gate — every assessment stays
// visible and takeable by everyone; this only determines which section it's
// grouped under and which career stages it's suggested to first.
export type LevelSection = "Foundational" | "Professional" | "Leadership" | "Executive";

export const LEVEL_SECTIONS: { key: LevelSection; label: string; blurb: string }[] = [
  { key: "Foundational", label: "Foundational", blurb: "Building blocks for students, job seekers, and early-career professionals." },
  { key: "Professional", label: "Professional", blurb: "Core competencies for established individual contributors." },
  { key: "Leadership", label: "Leadership & Management", blurb: "For anyone managing people or leading through others." },
  { key: "Executive", label: "Executive", blurb: "Senior/executive-scope judgment and organization-wide impact." },
];

export type Assessment = {
  slug: string;
  name: string;
  category: string;
  // Which of the 8 fixed Gap Analysis competency dimensions this assessment
  // maps to — lets Assessment-Center-driven plans reuse the same real,
  // per-format action library and book recommendations as Gap-Analysis-
  // driven plans, instead of a separate, more generic content system.
  dimension: import("../gap-analysis/dimensions").CompetencyDimension;
  description: string;
  level: LevelSection;
  questions: string[];
};

// Self-report Likert assessments (1 = Strongly disagree, 5 = Strongly agree).
// Proprietary heuristic scoring, designed to help someone understand their
// working style and blind spots more clearly — not a clinical instrument.
export const ASSESSMENTS: Assessment[] = [
  {
    slug: "leadership",
    name: "Leadership",
    category: "Leadership",
    dimension: "Leadership",
    description: "How you set direction, make decisions, and grow the people around you.",
    level: "Leadership",
    questions: [
      "I set clear direction for others even when the situation is ambiguous.",
      "I make timely decisions with incomplete information and own the outcome.",
      "I actively develop the people I work with, not just the work itself.",
      "I adjust my leadership approach based on the person and situation.",
      "I give and seek candid feedback, including feedback that's hard to hear.",
      "I build alignment across people who don't report to me when we need to work toward the same goal.",
      "I hold people accountable for commitments without becoming controlling.",
      "I make my reasoning visible so others can follow and challenge my thinking, not just my conclusion.",
      "I create an environment where people feel safe raising problems early, before they become crises.",
      "I recognize and credit others' contributions publicly, not just privately.",
      "I set a vision that others can rally around, not just a list of tasks.",
      "I know when to step back and let someone else lead.",
      "I address underperformance directly rather than letting it slide.",
    ],
  },
  {
    slug: "ai-literacy",
    name: "AI Literacy",
    category: "Digital & AI Skills",
    dimension: "AI & Digital Skills",
    description: "Your working fluency with AI tools, their limits, and applying them to real tasks.",
    level: "Foundational",
    questions: [
      "I regularly use AI tools to speed up or improve my actual work output.",
      "I can tell when an AI-generated answer is likely wrong or needs verification.",
      "I understand the basic tradeoffs of using AI (accuracy, bias, data privacy).",
      "I can write effective prompts to get useful results on the first or second try.",
      "I keep up with how AI is changing tools and expectations in my field.",
      "I know which of my tasks are a good fit for AI assistance and which aren't.",
      "I combine AI output with my own judgment rather than treating it as a final answer.",
      "I've changed how I work because of something an AI tool made possible.",
      "I'm comfortable explaining to a colleague how and why I used AI on a piece of work.",
      "I consider the reliability of the source data behind an AI tool before trusting its output.",
      "I understand that different AI models are better suited to different tasks.",
      "I catch it when an AI tool fabricates a plausible-sounding but false detail.",
      "I use AI to explore options rather than just to produce a final answer.",
    ],
  },
  {
    slug: "digital-skills",
    name: "Digital Skills",
    category: "Digital & AI Skills",
    dimension: "AI & Digital Skills",
    description: "Comfort and effectiveness with the digital tools your role actually depends on.",
    level: "Foundational",
    questions: [
      "I learn new software tools quickly without needing extensive training.",
      "I use data or dashboards to inform decisions rather than relying on instinct alone.",
      "I'm comfortable automating or streamlining a repetitive digital task.",
      "I know when to bring in a technical specialist versus solving it myself.",
      "My digital skills would be considered strong relative to peers in my role.",
      "I'm comfortable troubleshooting a technical problem myself before asking for help.",
      "I organize my digital files and information in a way that others could follow, not just myself.",
      "I evaluate new software or tools critically rather than adopting whatever is popular.",
      "I use keyboard shortcuts, templates, or other efficiency habits to speed up routine digital work.",
      "I stay reasonably current on the digital tools relevant to my role, even without formal training.",
      "I'm comfortable working across multiple connected tools rather than just one at a time.",
      "I protect sensitive data and follow basic security practices without being reminded.",
      "I can explain a technical limitation to a non-technical colleague without jargon.",
    ],
  },
  {
    slug: "emotional-intelligence",
    name: "Emotional Intelligence",
    category: "Interpersonal",
    dimension: "People Management",
    description: "Self-awareness and how you read and respond to the emotions of others.",
    level: "Professional",
    questions: [
      "I notice my own emotional reactions before they affect my decisions.",
      "I can accurately read how someone else is feeling, even if they don't say it directly.",
      "I stay composed and constructive during tense or conflict-heavy conversations.",
      "I adapt my communication style to the person I'm talking to.",
      "Colleagues would describe me as someone who is easy to work with under pressure.",
      "I can name what I'm feeling in the moment, not just after the fact.",
      "I notice when my own mood is affecting how I'm treating someone else.",
      "I can support a colleague who's struggling without taking on their problem as my own.",
      "I read non-verbal cues (tone, body language) as much as the actual words someone says.",
      "I repair a relationship after a tense moment rather than letting it linger unresolved.",
      "I recognize when someone is masking how they really feel.",
      "I can disagree with someone without damaging the relationship.",
      "I regulate my reactions rather than letting my first impulse drive my response.",
    ],
  },
  {
    slug: "personality",
    name: "Personality",
    category: "Self-Awareness",
    dimension: "Critical Thinking",
    description: "A broad self-report snapshot of working style and tendencies.",
    level: "Professional",
    questions: [
      "I'm energized by collaborating with others rather than working alone.",
      "I prefer structure and planning over spontaneity in how I work.",
      "I tend to take initiative rather than wait to be asked.",
      "I stay calm and steady rather than reactive when plans change suddenly.",
      "I'm generally comfortable taking a risk when the potential payoff is clear.",
      "I stay motivated on long projects even without regular external recognition.",
      "I actively seek other people's opinions before finalizing a decision that affects them.",
      "I feel comfortable being the one who speaks up first in a group.",
      "I adjust my plans readily when new information changes the picture.",
      "I hold up well when several priorities compete for my attention at once.",
      "I'm more energized by starting new things than by maintaining existing ones.",
      "I tend to think out loud rather than process internally before speaking.",
      "I set my own standards rather than relying mainly on external expectations.",
    ],
  },
  {
    slug: "communication",
    name: "Communication",
    category: "Interpersonal",
    dimension: "Communication",
    description: "How clearly and persuasively you get ideas across, in writing and in person.",
    level: "Foundational",
    questions: [
      "I can explain a complex idea simply to someone outside my area of expertise.",
      "My written communication is clear enough that it rarely needs clarifying follow-up.",
      "I adjust my message depending on whether I'm talking to peers, leaders, or clients.",
      "I'm comfortable presenting ideas to a group, including pushback or hard questions.",
      "I listen to understand before responding, rather than waiting for my turn to talk.",
      "I check that the other person actually understood my message, not just that I said it.",
      "I can summarize a long discussion into a few clear takeaways.",
      "I ask clarifying questions rather than guessing what someone means.",
      "I choose the right channel for a message (a call vs. an email vs. a quick chat) based on what it actually needs.",
      "I can deliver difficult news clearly without either softening it into confusion or being unnecessarily blunt.",
      "I tailor the level of detail I give based on how much time the other person actually has.",
      "I'm comfortable saying \"I don't know\" rather than bluffing an answer.",
      "I follow up in writing after important conversations so nothing gets lost.",
    ],
  },
  {
    slug: "learning-agility",
    name: "Learning Agility",
    category: "Growth",
    dimension: "Critical Thinking",
    description: "How quickly you pick up new skills and apply lessons from experience.",
    level: "Foundational",
    questions: [
      "I actively seek out unfamiliar challenges rather than staying in my comfort zone.",
      "I can apply a lesson learned in one context to a completely different situation.",
      "I ask for feedback proactively instead of waiting for a formal review.",
      "I recover quickly from mistakes and adjust my approach rather than repeating them.",
      "I pick up new tools, processes, or domains faster than most people I work with.",
      "I reflect on what I'd do differently after a project ends, even a successful one.",
      "I actively unlearn an old habit or belief once I find a better way of doing something.",
      "I seek out people who think differently than I do to challenge my assumptions.",
      "I treat being wrong as useful information rather than something to defend against.",
      "I can teach something I recently learned to someone else.",
      "I try a new approach even when my current one is working adequately.",
      "I can identify the specific skill I'm weakest at right now.",
      "I follow through on a development goal rather than losing momentum after the first attempt.",
    ],
  },
  {
    slug: "strategic-thinking",
    name: "Strategic Thinking",
    category: "Business Acumen",
    dimension: "Strategic Thinking",
    description: "Seeing the bigger picture and connecting daily work to longer-term goals.",
    level: "Leadership",
    questions: [
      "I can explain how my day-to-day work connects to broader organizational goals.",
      "I regularly think several steps ahead rather than reacting to what's in front of me.",
      "I can identify the highest-leverage priority among several competing options.",
      "I consider second-order consequences before committing to a plan.",
      "I'm comfortable making tradeoffs between short-term wins and long-term positioning.",
      "I can explain why a competitor's move matters, not just what they did.",
      "I look for patterns across seemingly unrelated problems or projects.",
      "I question whether a long-standing process still makes sense rather than assuming it does.",
      "I anticipate how a decision today will constrain or enable options later.",
      "I can articulate the \"why\" behind a strategy, not just the \"what.\"",
      "I distinguish between what's urgent and what's actually strategic.",
      "I consider multiple future scenarios rather than planning for just one outcome.",
      "I can identify which of my current efforts wouldn't matter if I stopped doing them.",
    ],
  },
  {
    slug: "problem-solving",
    name: "Problem Solving",
    category: "Cognitive",
    dimension: "Critical Thinking",
    description: "How you break down ambiguous problems and get to a workable solution.",
    level: "Professional",
    questions: [
      "I break large, ambiguous problems into smaller, solvable pieces.",
      "I look for root causes rather than treating symptoms.",
      "I generate more than one possible solution before picking an approach.",
      "I use data or evidence to test my assumptions before committing to a plan.",
      "I stay methodical rather than jumping to the first solution that comes to mind.",
      "I define the actual problem clearly before jumping to solutions.",
      "I know when a problem needs a quick fix versus a more thorough solution.",
      "I test a small version of a solution before committing to it fully.",
      "I ask \"what would have to be true\" for an assumption to hold before relying on it.",
      "I know when to stop analyzing and just make a decision.",
      "I involve the right people early rather than solving in isolation.",
      "I document what I tried, even the things that didn't work, for next time.",
      "I distinguish between a problem I can fully solve and one I can only manage.",
    ],
  },
  {
    slug: "critical-thinking",
    name: "Critical Thinking",
    category: "Cognitive",
    dimension: "Critical Thinking",
    description: "How rigorously you evaluate information, arguments, and your own assumptions.",
    level: "Professional",
    questions: [
      "I question my own assumptions before accepting a conclusion.",
      "I can identify weak reasoning or unsupported claims in an argument.",
      "I actively seek out perspectives that challenge my initial view.",
      "I distinguish between correlation and causation when evaluating evidence.",
      "I change my mind when presented with strong evidence, even if it's inconvenient.",
      "I notice when an argument relies on emotion rather than evidence.",
      "I consider who benefits from a claim before accepting it at face value.",
      "I can articulate the strongest version of an argument I disagree with.",
      "I check the source and credibility of information before repeating it.",
      "I recognize when I'm pattern-matching from a single example rather than reasoning from real evidence.",
      "I notice when I'm more convinced by how confidently something is stated than by the actual evidence.",
      "I separate my opinion of a person from my evaluation of their argument.",
      "I look for the strongest counter-evidence before settling on a conclusion.",
    ],
  },
  {
    slug: "creativity",
    name: "Creativity",
    category: "Cognitive",
    dimension: "Strategic Thinking",
    description: "Generating original ideas and connecting concepts across domains.",
    level: "Professional",
    questions: [
      "I regularly generate ideas that others describe as original or unexpected.",
      "I draw inspiration from outside my immediate field and apply it to my work.",
      "I'm comfortable proposing an idea that might not work, to see where it leads.",
      "I can reframe a stuck problem in a way that opens up new options.",
      "I build on other people's ideas rather than only generating my own from scratch.",
      "I combine existing ideas in ways others hadn't considered.",
      "I ask \"what if\" questions just to see where they lead, even without an immediate need.",
      "I'm comfortable with an idea being imperfect at first and refining it over time.",
      "I notice opportunities that aren't explicitly asked for.",
      "I use constraints (limited time, budget, resources) as a prompt for creativity rather than just an obstacle.",
      "I give myself unstructured time to think without an immediate deliverable in mind.",
      "I welcome critique of my ideas as a way to improve them, not just validate them.",
      "I notice when a \"best practice\" has become a limiting assumption rather than a genuine best option.",
    ],
  },
  {
    slug: "time-management",
    name: "Time Management",
    category: "Execution",
    dimension: "Critical Thinking",
    description: "How reliably you prioritize, plan, and deliver against deadlines.",
    level: "Foundational",
    questions: [
      "I consistently prioritize high-impact work over merely urgent work.",
      "I meet deadlines without regularly relying on last-minute pushes.",
      "I say no to (or renegotiate) low-value requests that would derail my priorities.",
      "I plan my week rather than reacting to whatever arrives first.",
      "I build in buffer time for the unexpected rather than scheduling back-to-back.",
      "I batch similar tasks together instead of constantly switching between different types of work.",
      "I estimate how long something will actually take reasonably accurately.",
      "I protect focused time on my calendar rather than letting it fill up automatically.",
      "I know my own most productive hours and use them for the hardest work.",
      "I finish tasks rather than leaving many things partially done at once.",
      "I renegotiate a deadline proactively when I see it slipping, rather than waiting until it's missed.",
      "I keep a reliable system for tracking commitments rather than relying on memory.",
      "I review my priorities regularly rather than setting them once and forgetting them.",
    ],
  },
  {
    slug: "resource-stewardship",
    name: "Resource & Budget Stewardship",
    category: "Execution",
    dimension: "Critical Thinking",
    description: "How responsibly you manage budget, tools, and materials — not just your time.",
    level: "Foundational",
    questions: [
      "I stay within an agreed budget rather than treating it as a rough guideline.",
      "I request only what I actually need rather than over-asking as a buffer.",
      "I track how a budget or set of resources is actually being used, not just what was allocated.",
      "I choose the cost-effective option when two choices deliver similar results.",
      "I flag early when a resource (budget, tools, materials) will run short, rather than waiting until it's gone.",
      "I consider the ongoing cost of a tool or subscription, not just the upfront price.",
      "I reuse or share existing resources instead of requesting new ones by default.",
      "I'm transparent about what I've spent or used, even when no one is directly checking.",
      "I look after shared or team resources as carefully as I would my own.",
      "I avoid hoarding extra resources 'just in case' when someone else could use them now.",
      "I weigh the total cost of ownership, not just the sticker price, before choosing a tool or vendor.",
      "I can explain why a resource request is necessary, not just that it would be nice to have.",
    ],
  },
  {
    slug: "resource-tradeoffs",
    name: "Trade-off Decision Making",
    category: "Execution",
    dimension: "Critical Thinking",
    description: "How you decide what to cut, delay, or scale back when time, budget, people, and tools are all limited at once.",
    level: "Foundational",
    questions: [
      "When I can't do everything, I make an explicit trade-off rather than trying to stretch every resource thin.",
      "I know when the right move is to cut scope versus extend the timeline versus ask for more resources.",
      "I communicate trade-offs to the people affected instead of quietly absorbing the impact myself.",
      "I distinguish what's actually required from what's just nice to have when resources are tight.",
      "I avoid continuing to invest in something just because I've already put resources into it.",
      "I think through the opportunity cost of committing a scarce resource before I commit it.",
      "I sequence work so I keep flexibility for later, rather than locking in every resource upfront.",
      "I raise a resource conflict proactively instead of waiting for it to become a crisis.",
      "I revisit an earlier trade-off decision when the constraints around it change.",
      "I avoid overcommitting the same limited resource to multiple things at once.",
      "I'm honest about my capacity limits rather than agreeing to more than I can realistically support.",
      "I put a scarce resource toward its highest-impact use rather than spreading it evenly by default.",
    ],
  },
  {
    slug: "resilience",
    name: "Resilience",
    category: "Self-Management",
    dimension: "Leadership",
    description: "How you sustain performance and recover under setbacks or sustained pressure.",
    level: "Leadership",
    questions: [
      "I recover relatively quickly from a significant setback at work.",
      "I maintain performance quality even during high-pressure periods.",
      "I can separate a difficult outcome from my sense of self-worth.",
      "I have reliable habits or routines that help me manage stress.",
      "I view failure as useful information rather than something to avoid discussing.",
      "I keep perspective on a bad day rather than letting it color everything else.",
      "I ask for support when I need it rather than trying to push through alone.",
      "I bounce back to my normal energy level within a reasonable time after a setback.",
      "I can identify what specifically triggers stress for me.",
      "I keep showing up consistently even during a difficult stretch, rather than disengaging.",
      "I can point to a specific coping strategy I use when things get hard.",
      "I distinguish between a setback that needs action and one that just needs time.",
      "I maintain relationships and support systems even when I'm busy or stressed.",
    ],
  },
  {
    slug: "change-readiness",
    name: "Change Readiness",
    category: "Adaptability",
    dimension: "Leadership",
    description: "How you respond when priorities, tools, or org structure shift under you.",
    level: "Leadership",
    questions: [
      "I adapt quickly when priorities or plans change with little notice.",
      "I look for the opportunity in organizational change rather than only the disruption.",
      "I help others adjust to change rather than adding to their resistance.",
      "I stay productive during periods of ambiguity or restructuring.",
      "I proactively update my skills when I see change coming, rather than waiting.",
      "I let go of the old way of doing things once a change has actually been made.",
      "I stay curious about a change rather than assuming the worst about it.",
      "I find the parts of a change I can influence rather than fixating on the parts I can't.",
      "I keep my commitments even when the environment around me is shifting.",
      "I notice early signals that something is about to change, rather than being caught off guard.",
      "I ask questions to understand the reasoning behind a change rather than assuming it's arbitrary.",
      "I distinguish between change that's cosmetic and change that actually matters.",
      "I recover my footing quickly after a change, rather than staying unsettled for a long stretch.",
    ],
  },
  {
    slug: "career-readiness",
    name: "Career Readiness",
    category: "Career",
    dimension: "Communication",
    description: "How prepared and intentional you are about your own career trajectory.",
    level: "Professional",
    questions: [
      "I have a clear view of what I want my next role to look like.",
      "I can articulate my strongest skills and value to a hiring manager or promotion panel.",
      "I actively build relationships and visibility beyond my immediate team.",
      "I track my accomplishments in a way I could use for a review or interview today.",
      "I regularly invest time in developing skills relevant to where I want to go next.",
      "I know what skills or experience are missing between me and my next role.",
      "I ask for feedback specifically about my readiness for the next level.",
      "I seek out projects that build visibility with people beyond my direct manager.",
      "I have a realistic sense of how I'm actually perceived at work, not just how I see myself.",
      "I take deliberate action toward my career goals rather than just hoping opportunities appear.",
      "I maintain relationships with former colleagues and mentors, not just my current team.",
      "I know what makes me distinct from others who want the same next role.",
      "I revisit and adjust my career goals periodically rather than setting them once.",
    ],
  },
  {
    slug: "executive-readiness",
    name: "Executive Readiness",
    category: "Leadership",
    dimension: "Leadership",
    description: "Preparedness for senior leadership scope — ambiguity, influence, and organization-wide impact.",
    level: "Executive",
    questions: [
      "I'm comfortable making decisions that affect people or teams beyond my own.",
      "I can influence outcomes without relying on formal authority alone.",
      "I think in terms of organizational tradeoffs, not just my function's priorities.",
      "I represent my organization credibly to external stakeholders or partners.",
      "I'm comfortable being accountable for outcomes I don't fully control.",
      "I make decisions with incomplete information when waiting for certainty isn't realistic.",
      "I build coalitions of support before a major decision, not just after.",
      "I balance competing stakeholder interests rather than favoring whoever is loudest.",
      "I hold a long-term view even when short-term pressure pushes against it.",
      "I take responsibility publicly for outcomes, including ones that didn't go well.",
      "I can operate effectively when the right answer is genuinely unclear, not just unknown to me personally.",
      "I develop other leaders, not just deliver results myself.",
      "I make decisions that are unpopular in the short term when they're right for the long term.",
    ],
  },
  {
    slug: "organizational-culture-stewardship",
    name: "Organizational Culture Stewardship",
    category: "Leadership",
    dimension: "Leadership",
    description: "How deliberately you shape and protect the culture your organization actually operates in — not just the one on the wall.",
    level: "Executive",
    questions: [
      "I can describe the culture I want, distinct from the one we actually have today.",
      "I notice when a behavior I'm rewarding contradicts a value I claim to hold.",
      "I address culture-eroding behavior from senior or high-performing people, not just easy targets.",
      "I treat culture as something to actively manage, not something that just happens on its own.",
      "I've changed a policy or process specifically because it was undermining the culture I want.",
      "I ask what a decision teaches people about what's actually valued here, not just its immediate outcome.",
      "I role-model the behaviors I want to see, including when it's inconvenient for me personally.",
      "I can point to a specific moment I let a short-term result slide to protect a cultural standard.",
      "I actively seek out dissenting views rather than only hearing from people who agree with me.",
      "I know what parts of our culture would break first under real pressure, and plan for that.",
      "I distinguish between culture as stated values and culture as what actually gets rewarded and promoted.",
      "I've walked back a decision after realizing it sent the wrong cultural signal.",
    ],
  },
  {
    slug: "leading-organizational-change",
    name: "Leading Organizational Change",
    category: "Strategy",
    dimension: "Strategic Thinking",
    description: "Sequencing, communicating, and sustaining a real organizational change — not just announcing one.",
    level: "Executive",
    questions: [
      "I can name specifically who loses something (status, control, familiarity) in a change I'm leading, not just who gains.",
      "I sequence a change in stages rather than expecting one announcement to shift behavior.",
      "I identify likely sources of resistance before they surface, not just react once they do.",
      "I keep communicating a change well past the point where I'm personally tired of talking about it.",
      "I distinguish between compliance with a change and genuine adoption of it.",
      "I build a coalition of visible supporters before rolling a change out broadly.",
      "I've killed or paused a change initiative when the evidence said it wasn't working.",
      "I set intermediate milestones so people can see a change is real progress, not just a promise.",
      "I address the emotional/identity cost of a change, not just the logistical one.",
      "I hold the line on a change's core intent while staying flexible on its implementation details.",
      "I check whether a change actually stuck months later, not just whether it launched successfully.",
      "I've explicitly asked people what they're worried about losing, rather than assuming I know.",
    ],
  },
  {
    slug: "delegation-team-development",
    name: "Delegation & Team Development",
    category: "Leadership",
    dimension: "People Management",
    description: "How effectively you hand off work and build capability in others, rather than just directing them.",
    level: "Leadership",
    questions: [
      "I delegate meaningful work, not just tasks I don't want to do myself.",
      "I match assignments to what will stretch and develop each person, not just what's convenient.",
      "I give people the context and authority they need to actually own a task, not just execute steps.",
      "I resist the urge to take back a delegated task the moment it gets difficult.",
      "I set clear expectations for outcomes when I delegate, rather than leaving them to guess.",
      "I check in at a cadence that supports someone without micromanaging them.",
      "I create individual development plans for the people I work with, not just team goals.",
      "I identify who on my team is ready for more responsibility before they ask for it.",
      "I give credit to the person who did the work, not myself, when a delegated task succeeds.",
      "I use mistakes on a delegated task as coaching moments rather than reasons to stop delegating.",
      "I build redundancy on my team so no single person, including me, is a bottleneck.",
      "I actively prepare at least one person who could step into my role if needed.",
      "I balance the short-term cost of delegating against the long-term gain in team capability.",
    ],
  },
  {
    slug: "business-acumen",
    name: "Business Acumen & Financial Literacy",
    category: "Business Acumen",
    dimension: "Financial Literacy",
    description: "How well you understand how the business actually makes money and use that to inform decisions.",
    level: "Professional",
    questions: [
      "I understand how my organization actually generates revenue, not just what my team does.",
      "I can read a basic budget or P&L well enough to spot what matters in it.",
      "I factor cost and return into decisions, not just whether something is a good idea.",
      "I understand who our customers or stakeholders are and what they actually value.",
      "I can explain how my day-to-day work affects the organization's bottom line.",
      "I understand the competitive landscape my organization operates in.",
      "I know the difference between a cost center and a revenue-generating function, and where my work sits.",
      "I ask about the business case before committing significant time to a project.",
      "I understand basic financial terms (margin, ROI, cash flow) well enough to follow a business conversation.",
      "I consider risk, not just opportunity, when evaluating a business decision.",
      "I understand how pricing, cost, and volume interact to affect profitability.",
      "I look at industry trends beyond my own function to understand where the business is headed.",
      "I can make a persuasive business case for an idea, not just a technical or operational one.",
    ],
  },
  {
    slug: "coaching-mentorship",
    name: "Coaching & Mentorship",
    category: "Leadership",
    dimension: "People Management",
    description: "How effectively you help someone else grow, through questions and feedback rather than just answers.",
    level: "Leadership",
    questions: [
      "I ask questions that help someone find their own answer rather than just telling them what to do.",
      "I give feedback that's specific and actionable, not just general encouragement or criticism.",
      "I adjust my coaching approach based on what the person actually needs, not a single fixed style.",
      "I make time for coaching conversations even when things are busy.",
      "I help people see a capability in themselves that they didn't recognize yet.",
      "I follow up on commitments made in a coaching conversation rather than letting them drop.",
      "I'm comfortable coaching someone on something I'm not personally an expert in.",
      "I listen for what's underneath what someone is saying, not just their literal words.",
      "I balance challenge and support so people grow without feeling unsupported.",
      "I celebrate someone else's growth as genuinely as I would my own.",
      "I help people learn from a mistake without shaming them for making it.",
      "I know when someone needs advice versus when they just need to be heard.",
      "I invest in people who may not report to me, not just my direct team.",
    ],
  },
  {
    slug: "networking",
    name: "Networking & Relationship Building",
    category: "Interpersonal",
    dimension: "Communication",
    description: "How intentionally you build and maintain a professional network beyond your immediate role.",
    level: "Foundational",
    questions: [
      "I maintain professional relationships even when I don't need anything from that person right now.",
      "I reach out to reconnect with people rather than only when I have an ask.",
      "I'm comfortable introducing myself to someone new in a professional setting.",
      "I follow up after meeting someone new rather than letting the connection fade.",
      "I offer help or value to my network before asking for anything in return.",
      "I attend or seek out events, communities, or conversations outside my immediate role.",
      "I remember and follow up on personal details people share with me.",
      "I connect people in my network to each other when it would help them.",
      "I maintain an online professional presence that reflects who I actually am.",
      "I ask for informational conversations to learn about roles or fields I'm curious about.",
      "I'm comfortable reaching out to someone more senior or more accomplished than me.",
      "I treat networking as building genuine relationships, not just collecting contacts.",
      "I know who in my network I could turn to for advice on a specific kind of problem.",
    ],
  },
];

export function getAssessment(slug: string) {
  return ASSESSMENTS.find((a) => a.slug === slug) ?? null;
}

export type ScoreBand = {
  min: number;
  max: number;
  label: string;
  interpretation: (name: string) => string;
  developmentAreas: string[];
};

export const SCORE_BANDS: ScoreBand[] = [
  {
    min: 0,
    max: 40,
    label: "Developing",
    interpretation: (name) =>
      `Your responses suggest ${name} is an area with real room to grow. That's a completely normal starting point — the value is in knowing where to focus.`,
    developmentAreas: [
      "Pick one specific, low-stakes situation this month to practice this deliberately.",
      "Ask a trusted colleague or manager for direct feedback on this area.",
      "Find a concrete resource (course, book, or mentor) focused specifically on this competency.",
    ],
  },
  {
    min: 41,
    max: 60,
    label: "Emerging",
    interpretation: (name) =>
      `You show inconsistent but real signal in ${name} — present in some situations, not yet a reliable strength.`,
    developmentAreas: [
      "Identify the specific situations where this competency shows up weakest and target those.",
      "Set a concrete, time-bound goal to practice this in a higher-stakes setting.",
      "Track instances over the next month to see the pattern more clearly.",
    ],
  },
  {
    min: 61,
    max: 80,
    label: "Proficient",
    interpretation: (name) =>
      `${name} looks like a solid, dependable strength based on your responses — something you can lean on.`,
    developmentAreas: [
      "Look for opportunities to mentor or model this competency for others.",
      "Push into higher-stakes or higher-visibility situations to stress-test it further.",
      "Pair this strength with an adjacent competency to compound its impact.",
    ],
  },
  {
    min: 81,
    max: 100,
    label: "Advanced",
    interpretation: (name) =>
      `${name} looks like a genuine differentiator for you — this is likely part of how others would describe your value.`,
    developmentAreas: [
      "Consider how to make this visible in performance reviews or promotion conversations.",
      "Look for roles or projects that specifically leverage this strength.",
      "Teach or codify what you do well here so it isn't just tacit knowledge.",
    ],
  },
];

export function scoreToBand(score: number): ScoreBand {
  return SCORE_BANDS.find((b) => score >= b.min && score <= b.max) ?? SCORE_BANDS[0];
}
