import LegalPageShell, { LegalSection } from "@/components/LegalPageShell";

export const metadata = { title: "Terms of Service — Devometrics" };

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated="July 3, 2026">
      <LegalSection title="1. What this covers">
        <p>
          These Terms govern your use of Devometrics, a product of Empiric Consultancy
          (&quot;Devometrics,&quot; &quot;we,&quot; &quot;us&quot;). By creating an account, you agree to these
          Terms. If you don&apos;t agree, don&apos;t use the product.
        </p>
      </LegalSection>

      <LegalSection title="2. Not career, financial, or professional advice — no guaranteed outcomes">
        <p>
          Devometrics is an AI-assisted guidance and development-planning tool. It is <strong>not</strong>{" "}
          a certified psychometric evaluation, a licensed career counseling service, or professional
          advice of any kind. Competency scores, gap analyses, assessment results, development
          plans, and AI Coach responses are generated by an AI model based on the information you
          provide, and can be wrong, incomplete, or not applicable to your specific situation.
        </p>
        <p>
          <strong>
            Using Devometrics does not guarantee any outcome — including career progression,
            promotion, a job offer, a raise, or any other professional result.
          </strong>{" "}
          Decisions about your career remain yours to make, and we recommend treating our output as
          one input among several, not a verdict.
        </p>
      </LegalSection>

      <LegalSection title="3. Pilot phase pricing">
        <p>
          Devometrics is currently in an early-access pilot. During this phase, all accounts
          receive full product access at no charge, regardless of any pricing tiers displayed on
          the site. Those tiers describe pricing we intend to introduce after the pilot period —
          we will notify pilot users before any billing begins.
        </p>
      </LegalSection>

      <LegalSection title="4. Your account">
        <p>
          You&apos;re responsible for the accuracy of information you provide and for keeping your
          login credentials secure. You must be legally able to enter into these Terms to use
          Devometrics.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable use">
        <p>
          Don&apos;t use Devometrics to upload content you don&apos;t have the right to share, to attempt
          to extract or reverse-engineer the underlying AI prompts or models, to abuse rate limits
          or attempt unauthorized access to other users&apos; data, or for any unlawful purpose.
        </p>
      </LegalSection>

      <LegalSection title="6. Your content">
        <p>
          You retain ownership of the CVs, job descriptions, assessment answers, and other content
          you submit. You grant us the limited right to process that content (including sending it
          to our AI provider) solely to provide the product to you. See our{" "}
          <a href="/privacy" style={{ color: "var(--teal)" }}>Privacy Policy</a> for how it&apos;s stored and
          for how long.
        </p>
      </LegalSection>

      <LegalSection title="7. Limitation of liability">
        <p>
          Devometrics is provided &quot;as is.&quot; To the maximum extent permitted by law, Empiric
          Consultancy is not liable for indirect, incidental, or consequential damages arising from
          your use of the product, including decisions made based on AI-generated guidance.
        </p>
      </LegalSection>

      <LegalSection title="8. Termination">
        <p>
          You can stop using Devometrics and delete your data at any time from your dashboard. We
          may suspend or terminate accounts that violate these Terms.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes">
        <p>
          We may update these Terms as the product changes, especially as pilot pricing transitions
          to billed pricing. We&apos;ll update the date at the top of this page when we do.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing law">
        <p>
          These Terms are governed by the laws of the jurisdiction where Empiric Consultancy is
          registered and operating. We&apos;ll name that jurisdiction precisely here once it&apos;s
          finalized with legal counsel.
        </p>
      </LegalSection>

      <LegalSection title="Questions">
        <p>
          Contact us at{" "}
          <a href="mailto:support@devometrics.com" style={{ color: "var(--teal)" }}>
            support@devometrics.com
          </a>{" "}
          with any questions about these Terms.
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
