import { NextResponse } from "next/server";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { createClient } from "@/lib/supabase/server";
import type { DevelopmentPlan, Milestone } from "@/lib/supabase/types";

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  const { data: plan } = await supabase
    .from("development_plans")
    .select("*")
    .eq("id", id)
    .eq("user_id", user.id)
    .single<DevelopmentPlan>();
  if (!plan) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { data: milestones } = await supabase
    .from("milestones")
    .select("*")
    .eq("plan_id", id)
    .order("position", { ascending: true })
    .returns<Milestone[]>();

  const list = milestones ?? [];
  const done = list.filter((m) => m.completed).length;

  const children: Paragraph[] = [
    new Paragraph({
      text: "Devometrics",
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 },
      children: [new TextRun({ text: "DEVOMETRICS", bold: true, color: "097066", size: 20 })],
    }),
    new Paragraph({
      text: plan.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 320 },
      children: [
        new TextRun({
          text: `${plan.horizon ? `${plan.horizon} plan · ` : ""}${done}/${list.length} milestones complete · Generated ${new Date(
            plan.created_at
          ).toLocaleDateString()}`,
          color: "666666",
          size: 20,
        }),
      ],
    }),
  ];

  if (list.length === 0) {
    children.push(new Paragraph({ text: "No milestones on this plan yet." }));
  }

  list.forEach((m, i) => {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 280, after: 80 },
        children: [new TextRun({ text: `${i + 1}. ${m.title}${m.completed ? "  ✓ Done" : ""}` })],
      })
    );
    if (m.description) {
      children.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [new TextRun({ text: m.description, size: 22 })],
        })
      );
    }
    const meta = [
      m.target_date ? `Target: ${m.target_date}` : null,
      m.weekly_hours ? `~${m.weekly_hours} hrs/${m.hours_period ?? "month"}` : null,
      m.budget_note,
    ].filter(Boolean);
    if (meta.length) {
      children.push(
        new Paragraph({
          spacing: { after: 40 },
          children: [new TextRun({ text: meta.join("  ·  "), color: "888888", size: 20 })],
        })
      );
    }
    if (m.success_indicator) {
      children.push(
        new Paragraph({
          spacing: { after: 160 },
          children: [
            new TextRun({ text: `Success indicator: ${m.success_indicator}`, italics: true, color: "097066", size: 20 }),
          ],
        })
      );
    }
  });

  children.push(
    new Paragraph({
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "AI-assisted development plan generated by Devometrics — not a certified professional evaluation or a guarantee of career outcomes.",
          italics: true,
          size: 16,
          color: "999999",
        }),
      ],
    })
  );

  const doc = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(doc);

  const safeName = plan.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "") || "development-plan";

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${safeName}.docx"`,
    },
  });
}
